# for cloud cannon
version: 3.1.2

# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Audio Video Systems
description: Audio Video Systems has been the trusted audio/video source for discerning clients since we opened our doors in 1977.
url: www.audiovideosystems.com

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: dist
exclude:

collections:
  work:
    output: true
    permalink: /our-work/:slug/

defaults:
  -
    scope:
      path: "index.html"
    values:
      layout: "home"
      class: "home"
  -
    scope:
      path: "about.html"
    values:
      layout: "default"
      class: "about"
      permalink: "/about/"
  -
    scope:
      path: "it-and-cloud-services.html"
    values:
      layout: "default"
      class: "cloud"
      permalink: "/it-and-cloud-services/"
  -
    scope:
      path: "home-automation.html"
    values:
      layout: "default"
      class: "automation"
      permalink: "/home-automation/"
  -
    scope:
      path: "home-theater.html"
    values:
      layout: "default"
      class: "theater"
      permalink: "/home-theater/"
  -
    scope:
      path: "lutron.html"
    values:
      layout: "default"
      class: "lutron"
      permalink: "/lutron/"
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: "project"
      class: "project"


careers: http://www.indeed.com/cmp/Audio-Video-Systems-1
facebook: https://www.facebook.com/AudioVideoSystemsInc
linkedin: https://www.linkedin.com/company/2491544



# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
# future: true
# show_drafts: true
# Disables the more accurate related posts for faster generating of the site
# lsi: false
# Only make the last 10 posts so generating isn't slow
# limit_posts: 10

# Permalink structure and pagination options
# permalink: none
# paginate: 10
# paginate_path: 'page:num'
# excerpt_separator: '<!--more-->'

# Markdown library and options
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true

# Extending Jekyll
gems:
  # - jekyll-archives
  # - jekyll-feed
  # - jekyll-gist
  - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-seo-tag

# Settings for archives
# jekyll-archives:
#   enabled:
#     - year
#     - month
#     - categories
#     - tags
#   layouts:
#     year: 'year-archive'
#     month: 'month-archive'
#     category: 'category-archive'
#     tag: 'tag-archive'
#   permalinks:
#     year: '/archive/:year/'
#     month: '/archive/:year/:month/'
#     category: '/category/:name/'
#     tags: '/tag/:name/'
